# Состояния диалога
(
    CHOOSING_ACTION,
    WAITING_NEW_TITLE,
    WAITING_STICKER,
    WAITING_EMOJI,
    WAITING_DECISION,
    WAITING_SHORT_NAME,
    WAITING_EXISTING_CHOICE,
    WAITING_PUBLISH_DECISION,
    WAITING_MANAGE_CHOICE,
) = range(9)

PAGE_PREV_LABEL = '⬅️ Назад'
PAGE_NEXT_LABEL = '➡️ Вперед'
CANCEL_LABEL = '⛔️ Отмена'

